### ISSUE TITLE
Plan of action

### ISSUE THREAD

**Issue by emmyft** [emmyft/mozfest19#8]
We need a plan for making the session happen. 

Deadline for this plan: Aug 14

**Comment by emmyft** [comment]
- [ ] wait for proposal to get accepted
- [ ] identify potential speakers (see #7) - both onsite and remote, aim for 7-10
- [ ] figure out travel needs for speakers
- [ ] division of labour - who does what?
